<?php

namespace Caencamp\ConfBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TalkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalkRepository extends EntityRepository
{
}
