caencamp_conf_homepage:
    pattern:  /
    defaults: { _controller: CaencampConfBundle:Default:index }
caencamp_add_talk:
    pattern:  /talk/add
    defaults: { _controller: CaencampConfBundle:Talk:addTalk }
caencamp_modify_talk:
    pattern:  /talk/modify/{id}
    defaults: { _controller: CaencampConfBundle:Talk:modifyTalk }